[package]
name = "p4-gdp"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
p4rs = { git = "https://github.com/oxidecomputer/p4", rev = "4645231880ccae40efd2bc583b643944ab0f0a20", package = "p4rs" }
p4-macro = { git = "https://github.com/oxidecomputer/p4", rev = "4645231880ccae40efd2bc583b643944ab0f0a20", package = "p4-macro" }
bitvec = "1.0"
colored = "3"
num = { version = "0.4", features = ["serde"] }
usdt = "0.5.0"

[dev-dependencies]
smolgnet = { path = ".." }
rand = "0.9.2"
